import Head from "next/head";
import CountDown from "./../components/CountDown";
import { ChangeEvent } from "react";
import { useState } from "react";

export default function Home() {
  const [startTimer, setStartTimer] = useState<boolean>(false);
  type Game = "waiting for input" | "in progress" | "game over";
  type Word = string;

  let game: Game = "waiting for input";

  let wordsInDom: Word[] = "sentence to test".split("");

  let words: Word[] = "sentence to test".split(" ");

  let wordIndex = 0;
  let letterIndex = -1;

  const onFocus = () => {
    game = "in progress";
    setStartTimer(true);
  };

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    let lastLetterTyped: string = e.target.value.slice(-1);

    if (letterIndex < words[wordIndex].length - 1) {
      letterIndex += 1;

      if (words[wordIndex][letterIndex] === lastLetterTyped) {
        console.log("correct");
      } else {
        console.log("incorrect");
      }

      if (wordIndex === words.length - 1 && letterIndex === words[wordIndex].length - 1) {
        console.log("Game Finished");
      }
    } else if (lastLetterTyped === " ") {
      wordIndex += 1;
      letterIndex = -1;
    } else {
      console.log("incorrect");
    }
  };

  return (
    <div className="bg-slate-600 h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col align-center justify-center h-screen w-fit mx-auto">
        <CountDown startTimer={startTimer} />
        <input type="text" onFocus={onFocus} onChange={handleChange} />
        <div className="text-center mt-2">
          {wordsInDom.map((word, index) => (
            <span key={index}>{word}</span>
          ))}
        </div>
      </div>
    </div>
  );
}
